 defaults:
    -
        scope:
            path: ""
        values:
            layout: "base"
prose:
        rooturl: "/"
        siteurl: "http://spartronics5048.com"
        media: "/images/"
        ignore:
                - ".gitignore"
                - "CNAME"
                - "README.md"
                - "_config.ym;"
                - "_include/"
                - "_layouts/"
                - "scripts/"
                - "css/"
                - "About/index.html"
                - "TeamHub/index.html"
        metadata:
                /:
                        - name: "title"
                          field:
                                  element: "texr"
                                  label: "Title"
                                  value: ""

