defaults:
    -
        scope:
            path: ""
        values:
            layout: "base"
prose:
    rooturl: ""
    siteurl: "http://spartronics5048.com"
    media: "images"
    ignore: 
        - '.gitignore'
        - 'CNAME'
        - '_config.yml'
        - '_includes'
        - '_layouts'
        - 'scripts'
        - 'css'
        - 'About/index.html'
        - 'TeamHub/index.html'
        - 'fonts'
                
    metadata:
        /:
          - name: "title"
            field:
                element: "text"
                label: "Title"
                value: ""
